spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/proxyip?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    hikari:
      max-lifetime: 30000

server:
  port: 9050
  servlet:
    context-path: /proxy

logback:
  level:
    #logback-spring.xml中的LOG_LEVEL_ROOT属性
    root: info
    #logback-spring.xml中的LOG_LEVEL_COMMON属性
    common: info