spring:
  datasource:
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/proxyip?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    driver-class-name: net.sf.log4jdbc.DriverSpy
    username: root
    password: 123456
    hikari:
      max-lifetime: 30000

server:
  port: 9050
  servlet:
    context-path: /proxy

logback:
  level:
    #logback.xml中的LOG_LEVEL_ROOT属性
    root: info
    #logback.xml中的LOG_LEVEL_COMMON属性
    common: info